# Generated by Django 3.0.5 on 2020-04-07 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_auto_20200405_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlshortener',
            options={'verbose_name': 'Url Abbreviato', 'verbose_name_plural': 'Url Abbreviati'},
        ),
    ]
