# Generated by Django 3.0.5 on 2020-04-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0003_auto_20200407_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='shorten_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
